In [1]:
import pandas as pd
countries = pd.read_csv('countries.csv')

In [2]:
countries.head()

,DimensionCode,DimensionMemberCode,DisplayString,DisplaySequence,URL,DS,FIPS,GEOMETRY,IOC,ISO,...,SHORTNAMEFR,WHO,WHOLEGALSTATUS,WHO_REGION,WHO_REGION_CODE,WMO,WORLD_BANK_INCOME_GROUP,WORLD_BANK_INCOME_GROUP_CODE,WORLD_BANK_INCOME_GROUP_GNI_REFERENCE_YEAR,WORLD_BANK_INCOME_GROUP_RELEASE_DATE
0,COUNTRY,AFG,Afghanistan,10,NaN,AFG,AF,AFG,AFG,AFG,...,Afghanistan,AFG,M,Eastern Mediterranean,EMR,AF,Low-income,WB_LI,2015.0,2016.0
1,COUNTRY,ALB,Albania,20,NaN,AL,AL,ALB,ALB,ALB,...,Albanie,ALB,M,Europe,EUR,AB,Upper-middle-income,WB_UMI,2015.0,2016.0
2,COUNTRY,DZA,Algeria,30,NaN,DZ,AG,DZA,ALG,DZA,...,Algérie,ALG,M,Africa,AFR,AL,Upper-middle-income,WB_UMI,2015.0,2016.0
3,COUNTRY,AND,Andorra,40,NaN,AND,AN,AND,AND,AND,...,Andorre,AND,M,Europe,EUR,NaN,High-income,WB_HI,2015.0,2016.0
4,COUNTRY,AGO,Angola,50,NaN,NaN,AO,AGO,ANG,AGO,...,Angola,ANG,M,Africa,AFR,AN,Upper-middle-income,WB_UMI,2015.0,2016.0

In [3]:
#slicing the columns that we need
#we use 'DislpayString' insted of 'SHORTNAMEFR' this time
countries = countries[['DisplayString','WHO_REGION','WORLD_BANK_INCOME_GROUP']]

In [4]:
#countries[countries.WORLD_BANK_INCOME_GROUP.isnull()]
countries=countries.dropna()    #drop the null values
countries.isnull().sum()

DisplayString              0
WHO_REGION                 0
WORLD_BANK_INCOME_GROUP    0
dtype: int64